"use client";
 
import Image from "next/image";
import ContactSection from "@/app/components/ContactSection";
 
export default function AboutPage() {
  return (
    <main className="bg-gradient-to-br from-gray-50 via-white to-gray-100 text-gray-800">
 
      {/* HERO SECTION */}
      <section className="max-w-7xl mx-auto px-6 py-20 grid md:grid-cols-2 gap-12 items-center">
 
        {/* Left Content */}
        <div>
          <h1 className="text-4xl md:text-5xl font-bold leading-tight">
            What is{" "}
            <span className="text-[#c8a46a]">PravRaha</span>? <br />
            <span className="text-xl md:text-2xl font-semibold text-gray-600">
              The B2B GTM Platform Built on One Principle: <br />
              <span className="text-[#c8a46a]">Precision Over Volume</span>
            </span>
          </h1>
 
          <div className="w-20 h-1 bg-[#c8a46a] mt-4 mb-6 rounded"></div>
 
          <p className="text-gray-600 leading-relaxed mb-4">
            PravRaha comes from the Sanskrit word for{" "}
            <span className="font-semibold text-[#c8a46a]">
              &ldquo;High Quality,&rdquo;
            </span>{" "}
            and that is not just a name, it is the standard we hold every data
            point, every outreach sequence, and every meeting we book to.
            Founded in Ranchi, Jharkhand by a former Amazon and enterprise sales
            operator, PravRaha was built because most B2B data tools overpromise
            and underdeliver.
          </p>
 
          {/* Highlighted paragraph */}
          <p className="text-gray-600 leading-relaxed">
            To us, high quality means a{" "}
            <span className="text-[#c8a46a] font-semibold">
              95%+ email deliverability rate
            </span>
            , intent signals sourced from{" "}
            <span className="text-[#c8a46a] font-semibold">
              100+ intelligence layers
            </span>
            , and outreach sequences written by trained SDRs not generated by a
            template. It means your sales team gets meetings with decision-makers
            who are actually in-market.{" "}
            <span className="text-[#c8a46a] font-semibold">
              That&apos;s the standard. That&apos;s PravRaha.
            </span>
          </p>
        </div>
 
        {/* Right Image */}
        <div className="relative h-72 md:h-[420px] rounded-3xl overflow-hidden shadow-2xl group">
          <Image
            src="/business.jpg"
            alt="About PravRaha"
            fill
            className="object-cover group-hover:scale-105 transition duration-500"
          />
 
          <div className="absolute inset-0 bg-black/20"></div>
 
          <div className="absolute bottom-4 left-4 right-4 bg-white/20 backdrop-blur-xl border border-white/30 rounded-xl p-4 shadow-lg">
            <p className="text-sm text-white">
              The PravRaha team-B2B GTM intelligence built in Ranchi,
              delivered globally.
            </p>
          </div>
        </div>
      </section>
 
      {/* WHAT WE OFFER */}
      <section className="py-24 relative">
        <div className="absolute inset-0 bg-gradient-to-r from-[#c8a46a]/10 via-transparent to-[#6c8486]/10 blur-3xl"></div>
 
        <div className="max-w-7xl mx-auto px-6 text-center relative">
          <h2 className="text-4xl md:text-5xl font-bold">
            B2B Lead Generation Platform + SDR Led Outreach Services In One Place
          </h2>
          <div className="w-20 h-1 bg-[#c8a46a] mx-auto mt-4 mb-14 rounded"></div>
 
          <div className="grid md:grid-cols-2 gap-12 items-stretch">
 
            {/* Product Card */}
            <div className="relative group flex h-full">
              <div className="absolute inset-0 bg-[#c8a46a]/30 blur-2xl opacity-0 group-hover:opacity-100 transition"></div>
 
              <div className="relative bg-white/30 backdrop-blur-2xl border border-white/40 rounded-3xl shadow-xl hover:-translate-y-3 transition duration-300 overflow-hidden flex flex-col h-full w-full">
                <div className="h-1 w-full bg-gradient-to-r from-[#c8a46a] to-yellow-300"></div>
 
                <div className="p-10 md:p-12 flex flex-col justify-between h-full text-center">
                  <div>
                    <h3 className="text-2xl md:text-3xl font-semibold mb-4 text-[#c8a46a]">
                      GTM Intelligence Platform
                    </h3>
                    <p className="text-base md:text-lg leading-relaxed text-gray-700">
                      PravRaha&apos;s GTM intelligence platform combines a proprietary
                      B2B contact database, real-time buyer intent data, and
                      multi-layer account enrichment-giving your sales team the
                      data infrastructure to target the right accounts and the SDR
                      execution layer to actually reach them.
                    </p>
                  </div>
                </div>
              </div>
            </div>
 
            {/* Services Card */}
            <div className="relative group flex h-full">
              <div className="absolute inset-0 bg-[#6c8486]/30 blur-2xl opacity-0 group-hover:opacity-100 transition"></div>
 
              <div className="relative bg-white/30 backdrop-blur-2xl border border-white/40 rounded-3xl shadow-xl hover:-translate-y-3 transition duration-300 overflow-hidden flex flex-col h-full w-full">
                <div className="h-1 w-full bg-gradient-to-r from-[#6c8486] to-teal-300"></div>
 
                <div className="p-10 md:p-12 flex flex-col justify-between h-full text-center">
                  <div>
                    <h3 className="text-2xl md:text-3xl font-semibold mb-4 text-[#6c8486]">
                      SDR-Led Outbound Prospecting Services
                    </h3>
                    <p className="text-base md:text-lg leading-relaxed text-gray-700">
                      For teams who want the results without building the function,
                      PravRaha&apos;s SDR team runs your full outbound motion: ICP
                      definition, contact sourcing, personalised sequences, and
                      meeting booking. You own the pipeline. We do the prospecting.
                    </p>
                  </div>
                </div>
              </div>
            </div>
 
          </div>
        </div>
      </section>
 
      {/* CORE VALUES */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold">
            The Principles Behind Every Prospect List, Every Sequence, Every Meeting We Book
          </h2>
          <div className="w-16 h-1 bg-[#c8a46a] mx-auto mt-3 mb-12 rounded"></div>
 
          <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-6">
            {[
              {
                title: "Precision Over Volume",
                desc: "We constantly evolve.",
                img: "/about1.jpg",
              },
              {
                title: "Meetings That Matter",
                desc: "We measure our success by one number: qualified meetings booked for our clients.",
                img: "/about2.jpg",
              },
              {
                title: "Signal-Led, Not Assumption Led",
                desc: "We reach prospects when the data says they're ready.",
                img: "/about3.jpg",
              },
              {
                title: "Full Visibility, No Black Box",
                desc: "You see every prospect we target, every sequence we send, every reply we get.",
                img: "/business.jpg",
              },
            ].map((item, i) => (
              <div
                key={i}
                className="rounded-2xl overflow-hidden shadow-md group hover:shadow-2xl transition flex flex-col h-full"
              >
                <div className="relative h-40">
                  <Image
                    src={item.img}
                    alt={item.title}
                    fill
                    className="object-cover group-hover:scale-110 transition"
                  />
                </div>
 
                <div className="bg-[#6c8486] text-white p-4 text-left flex-1 flex flex-col">
                  <h4 className="font-semibold">{item.title}</h4>
                  <p className="text-sm opacity-90 mt-2">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
 
      <ContactSection />
    </main>
  );
}